# Generated by Django 5.1.6 on 2025-03-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person.', max_length=255)),
                ('domain', models.CharField(blank=True, help_text="club domain (e.g., 'MAC', 'Design').", max_length=255)),
                ('role', models.CharField(blank=True, help_text="Current role (e.g., 'web developer', 'Cloud Engineer').", max_length=255)),
                ('linkedin', models.URLField(blank=True, help_text='LinkedIn profile URL.', max_length=255)),
                ('instagram', models.URLField(blank=True, help_text='Instagram profile URL.', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='Email address.', max_length=254)),
                ('github', models.URLField(blank=True, help_text='GitHub profile URL.', max_length=255)),
            ],
            options={
                'verbose_name': 'Person Profile',
                'verbose_name_plural': 'Person Profiles',
                'ordering': ['name'],
            },
        ),
    ]
